### ISSUE TITLE
Implement endpoint scanning

### ISSUE THREAD

**Issue by isabeleliassen** [csg-org/licensure-compact-system#28]
### Acceptance Criteria
- Scanning is set up in compliance with the QASP

### Useful links / document

**Comment by jusdino** [comment]
I downloaded OWASP ZAP and pointed it at my API endpoint to run, though that had little benefit since the tool seems designed to be used with an actual web app. Not a lot is specified in the QASP about how much is to be done with the tool. I think we've met the requirement, though we should revisit once we have more AWS accounts stood up and have a long-lived web app started that we can point the tool at. Automation will be beneficial at that point.
